server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/preorder
    username: root
    password: 1234

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: alex.yb.dev@gmail.com
    password: wlbbolxdrmfethav
    default-encoding: utf-8
    properties:
      debug: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

#  sql:
#    init:
#      mode: always

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace

jwt:
  header: Authorization
  secret: asdDfas89123askdklAJSdvnakldeiqsa52135azdwv
  access-token:
    expiration: 1800000 # 30분
  refresh-token:
    expiration: 604800000 # 7일