# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file:
      - env_file.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  http-request-tool:
    image: http-request-tool
    restart: always
    build:
      context: http-request-tool
      dockerfile: Dockerfile
