# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  payment-test:
    image: payment-test
    build:
      context: ./simulation-test
      dockerfile: Dockerfile
    command: [ "python", "payment_test.py" ]

  reservation-stock-test:
    image: reservation-stock-test
    build:
      context: ./simulation-test
      dockerfile: Dockerfile
    command: [ "python", "reservation_stock_test.py" ]
