server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/preorder
    username: root
    password: 1234

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: alex.yb.dev@gmail.com
    password: wlbbolxdrmfethav
    default-encoding: utf-8
    properties:
      debug: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.sql: debug

jwt:
  header: Authorization
  secret: asdDfas89123askdklAJSdvnakldeiqsa52135azdwv
  expiration-in-second: 86400000